[book]
authors = ["wendajiang"]
language = "zh"
multilingual = false
src = "src"
title = "Effective Modern C++"

[output.html]
mathjax-support = true
no-section-label = true
git-repository-url = "https://github.com/CnTransGroup/EffectiveModernCppChinese"
git-repository-icon = "fa-github"
